name: Smithery Flamecast
description: Run Claude Code to make changes and open a PR

inputs:
  prompt:
    description: "Prompt for Claude Code"
    required: true
  base_branch:
    description: "Base branch for the PR"
    required: false
    default: "main"
  target_repo:
    description: "Target repo (e.g. owner/repo). Leave empty for current repo."
    required: false
  claude_code_oauth_token:
    description: "Claude Code OAuth token"
    required: true
  flamecast_pat:
    description: "GitHub PAT for cross-repo operations"
    required: false

outputs:
  execution_file:
    description: "Path to Claude Code execution output"
    value: ${{ steps.claude.outputs.execution_file }}
  pr_url:
    description: "Created or existing pull request URL (empty when no PR)"
    value: ${{ steps.pr.outputs.url }}

runs:
  using: composite
  steps:
    - name: Generate branch name
      id: branch
      shell: bash
      env:
        PROMPT: ${{ inputs.prompt }}
      run: |
        SLUG=$(echo "$PROMPT" | tr '[:upper:]' '[:lower:]' | tr -cs '[:alnum:]' '-' | cut -c1-20 | sed 's/-$//')
        HASH=$(echo -n "$PROMPT" | sha256sum | head -c 7)
        USER="${GITHUB_ACTOR}"
        echo "name=flamecast/${USER}/${SLUG}-${HASH}" >> "$GITHUB_OUTPUT"

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target_repo || github.repository }}
        token: ${{ inputs.target_repo && inputs.flamecast_pat || github.token }}
        fetch-depth: 0

    - name: Configure git identity
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.target_repo && inputs.flamecast_pat || github.token }}
      run: |
        USER_JSON=$(gh api /users/"$GITHUB_ACTOR")
        USER_NAME=$(echo "$USER_JSON" | jq -r '.name // .login')
        USER_ID=$(echo "$USER_JSON" | jq -r '.id')
        git config user.name "$USER_NAME"
        git config user.email "${USER_ID}+${GITHUB_ACTOR}@users.noreply.github.com"

    - name: Switch to branch
      shell: bash
      env:
        BRANCH: ${{ steps.branch.outputs.name }}
        BASE: ${{ inputs.base_branch || 'main' }}
      run: |
        git fetch origin
        if git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
          git checkout "$BRANCH"
        else
          git checkout "$BASE" 2>/dev/null || git checkout "origin/$BASE"
          git checkout -b "$BRANCH"
        fi

    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action@main
      with:
        prompt: ${{ inputs.prompt }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        github_token: ${{ inputs.target_repo && inputs.flamecast_pat || github.token }}
        base_branch: ${{ inputs.base_branch || 'main' }}
        claude_args: |
          --dangerously-skip-permissions

    - name: Check for changes
      id: commit
      shell: bash
      env:
        BRANCH: ${{ steps.branch.outputs.name }}
      run: |
        # Claude may have already committed+pushed, or may have left uncommitted changes
        if ! git diff --quiet || ! git diff --cached --quiet; then
          # Uncommitted changes exist — commit them
          git add -A
          git commit -m "flamecast: apply changes"
          git push origin "$BRANCH"
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        elif [ "$(git rev-list origin/$BRANCH..HEAD 2>/dev/null | wc -l)" -gt 0 ] 2>/dev/null; then
          # Commits exist but haven't been pushed
          git push origin "$BRANCH"
          echo "has_changes=true" >> "$GITHUB_OUTPUT"
        elif git ls-remote --exit-code --heads origin "$BRANCH" > /dev/null 2>&1; then
          # Branch exists on remote — check if it has changes vs base
          BASE="${{ inputs.base_branch || 'main' }}"
          if ! git diff --quiet "origin/$BASE..origin/$BRANCH" 2>/dev/null; then
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
          else
            echo "No changes to commit"
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
          fi
        else
          echo "No changes to commit"
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Open or update PR
      id: pr
      if: steps.commit.outputs.has_changes == 'true'
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.target_repo && inputs.flamecast_pat || github.token }}
        PROMPT: ${{ inputs.prompt }}
        BRANCH: ${{ steps.branch.outputs.name }}
        BASE: ${{ inputs.base_branch || 'main' }}
        TARGET_REPO: ${{ inputs.target_repo }}
      run: |
        REPO_FLAG=""
        if [ -n "$TARGET_REPO" ]; then
          REPO_FLAG="--repo $TARGET_REPO"
        fi
        TITLE="flamecast: $(echo "$PROMPT" | head -c 72)"
        if gh pr view "$BRANCH" $REPO_FLAG --json state -q '.state' 2>/dev/null | grep -q OPEN; then
          echo "PR already exists"
        else
          gh pr create \
            --base "$BASE" \
            --head "$BRANCH" \
            --title "$TITLE" \
            --body "Prompted by: ${PROMPT}" \
            $REPO_FLAG
        fi
        PR_URL=$(gh pr view "$BRANCH" $REPO_FLAG --json url -q '.url')
        echo "url=$PR_URL" >> "$GITHUB_OUTPUT"
