name: Smithery Flamecast
description: Run Claude Code to make changes and open a PR

inputs:
  prompt:
    description: "Prompt for Claude Code"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth token"
    required: true
  flamecast_pat:
    description: "GitHub PAT for cross-repo operations"
    required: false

runs:
  using: composite
  steps:
    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action@main
      with:
        prompt: ${{ inputs.prompt }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        github_token: ${{ inputs.flamecast_pat }}
        base_branch: ${{ inputs.base_branch || 'main' }}
        claude_args: |
          --dangerously-skip-permissions
