name: Smithery Flamecast
description: Run Claude Code to make changes and open a PR

inputs:
  prompt:
    description: "Prompt for Claude Code"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth token"
    required: true
  flamecast_pat:
    description: "GitHub PAT for cross-repo operations"
    required: false
  connections:
    description: "JSON object of MCP connections: {name: {server, url}}"
    required: false
  flamecast_api_key:
    description: "Smithery Connect token for MCP server authentication"
    required: false
  show_full_output:
    description: "Show full Claude Code output in logs (WARNING: may expose secrets)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Configure git identity
      id: user
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.flamecast_pat || github.token }}
      run: |
        USER_ID=$(gh api /users/"$GITHUB_ACTOR" --jq '.id')
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${USER_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        echo "id=$USER_ID" >> "$GITHUB_OUTPUT"

    - name: Generate MCP config
      id: mcp
      if: ${{ inputs.connections != '' && inputs.flamecast_api_key != '' }}
      shell: bash
      env:
        CONNECTIONS_JSON: ${{ inputs.connections }}
        FLAMECAST_API_KEY: ${{ inputs.flamecast_api_key }}
      run: |
        # Build mcpServers object from connections JSON
        MCP_CONFIG=$(echo "$CONNECTIONS_JSON" | jq -c --arg token "$FLAMECAST_API_KEY" '{
          mcpServers: (to_entries | map({
            key: .key,
            value: {
              type: "http",
              url: .value.url,
              headers: {
                "smithery-connection": $token
              }
            }
          }) | from_entries)
        }')

        echo "$MCP_CONFIG" > /tmp/flamecast-mcp-config.json
        echo "config_path=/tmp/flamecast-mcp-config.json" >> "$GITHUB_OUTPUT"
        echo "Generated MCP config with $(echo "$CONNECTIONS_JSON" | jq 'length') server(s)"

    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action@main
      with:
        prompt: ${{ inputs.prompt }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        github_token: ${{ inputs.flamecast_pat }}
        base_branch: ${{ inputs.base_branch || 'main' }}
        bot_id: ${{ steps.user.outputs.id }}
        bot_name: ${{ github.actor }}
        show_full_output: ${{ inputs.show_full_output }}
        claude_args: |
          --dangerously-skip-permissions
          ${{ steps.mcp.outputs.config_path && format('--mcp-config {0}', steps.mcp.outputs.config_path) || '' }}
