name: Smithery Flamecast
description: Run Claude Code to make changes and open a PR

inputs:
  prompt:
    description: "Prompt for Claude Code"
    required: true
  claude_code_oauth_token:
    description: "Claude Code OAuth token"
    required: true
  flamecast_pat:
    description: "GitHub PAT for cross-repo operations"
    required: false
  connections:
    description: "JSON object of MCP connections: {name: {server, url, connectionId}}"
    required: false
  flamecast_api_key:
    description: "Smithery Connect token for MCP server authentication"
    required: false
  show_full_output:
    description: "Show full Claude Code output in logs (WARNING: may expose secrets)"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Configure git identity
      id: user
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.flamecast_pat || github.token }}
      run: |
        USER_ID=$(gh api /users/"$GITHUB_ACTOR" --jq '.id')
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "${USER_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
        echo "id=$USER_ID" >> "$GITHUB_OUTPUT"

    - name: Install Smithery CLI
      if: ${{ inputs.connections != '' && inputs.flamecast_api_key != '' }}
      shell: bash
      run: npm install -g @smithery/cli@latest

    - name: Configure Smithery CLI
      id: smithery
      if: ${{ inputs.connections != '' && inputs.flamecast_api_key != '' }}
      shell: bash
      env:
        SMITHERY_API_KEY: ${{ inputs.flamecast_api_key }}
        CONNECTIONS_JSON: ${{ inputs.connections }}
      run: |
        # Set the flamecast namespace
        smithery namespace use flamecast

        # List connection names for the prompt
        NAMES=$(echo "$CONNECTIONS_JSON" | jq -r 'keys[]')
        echo "connection_names=$NAMES" >> "$GITHUB_OUTPUT"
        echo "Smithery CLI configured with connections: $NAMES"

    - name: Build Claude Code settings
      id: settings
      if: ${{ inputs.connections != '' && inputs.flamecast_api_key != '' }}
      shell: bash
      env:
        FLAMECAST_API_KEY: ${{ inputs.flamecast_api_key }}
      run: |
        # Pass SMITHERY_API_KEY through to Claude Code's environment
        SETTINGS=$(jq -nc --arg key "$FLAMECAST_API_KEY" '{env: {SMITHERY_API_KEY: $key}}')
        echo "json=$SETTINGS" >> "$GITHUB_OUTPUT"

    - name: Run Claude Code
      id: claude
      uses: anthropics/claude-code-action@main
      with:
        prompt: ${{ inputs.prompt }}
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        github_token: ${{ inputs.flamecast_pat }}
        base_branch: ${{ inputs.base_branch || 'main' }}
        bot_id: ${{ steps.user.outputs.id }}
        bot_name: ${{ github.actor }}
        show_full_output: ${{ inputs.show_full_output }}
        settings: ${{ steps.settings.outputs.json || '' }}
        claude_args: "--dangerously-skip-permissions"
