import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { AuthKitProvider } from "@workos-inc/authkit-nextjs/components"
import { Toaster } from "@/components/ui/sonner"
import { QueryProvider } from "@/lib/query-client-provider"
import "./globals.css"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthKitProvider>
					<QueryProvider>{children}</QueryProvider>
				</AuthKitProvider>
				<Toaster />
			</body>
		</html>
	)
}
