/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoPosthogRouteImport } from './routes/demo/posthog'
import { Route as OwnerRepoIndexRouteImport } from './routes/$owner/$repo/index'
import { Route as OwnerRepoChatChatIdRouteImport } from './routes/$owner/$repo/chat/$chatId'
import { Route as OwnerRepoActionsRunsRunIdRouteImport } from './routes/$owner/$repo/actions/runs/$runId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPosthogRoute = DemoPosthogRouteImport.update({
  id: '/demo/posthog',
  path: '/demo/posthog',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoIndexRoute = OwnerRepoIndexRouteImport.update({
  id: '/$owner/$repo/',
  path: '/$owner/$repo/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoChatChatIdRoute = OwnerRepoChatChatIdRouteImport.update({
  id: '/$owner/$repo/chat/$chatId',
  path: '/$owner/$repo/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRepoActionsRunsRunIdRoute =
  OwnerRepoActionsRunsRunIdRouteImport.update({
    id: '/$owner/$repo/actions/runs/$runId',
    path: '/$owner/$repo/actions/runs/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/chat/$chatId': typeof OwnerRepoChatChatIdRoute
  '/$owner/$repo/actions/runs/$runId': typeof OwnerRepoActionsRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/$owner/$repo': typeof OwnerRepoIndexRoute
  '/$owner/$repo/chat/$chatId': typeof OwnerRepoChatChatIdRoute
  '/$owner/$repo/actions/runs/$runId': typeof OwnerRepoActionsRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/demo/posthog': typeof DemoPosthogRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/$owner/$repo/': typeof OwnerRepoIndexRoute
  '/$owner/$repo/chat/$chatId': typeof OwnerRepoChatChatIdRoute
  '/$owner/$repo/actions/runs/$runId': typeof OwnerRepoActionsRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/$owner/$repo/'
    | '/$owner/$repo/chat/$chatId'
    | '/$owner/$repo/actions/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/$owner/$repo'
    | '/$owner/$repo/chat/$chatId'
    | '/$owner/$repo/actions/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/demo/posthog'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/$owner/$repo/'
    | '/$owner/$repo/chat/$chatId'
    | '/$owner/$repo/actions/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  DemoPosthogRoute: typeof DemoPosthogRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  OwnerRepoIndexRoute: typeof OwnerRepoIndexRoute
  OwnerRepoChatChatIdRoute: typeof OwnerRepoChatChatIdRoute
  OwnerRepoActionsRunsRunIdRoute: typeof OwnerRepoActionsRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/posthog': {
      id: '/demo/posthog'
      path: '/demo/posthog'
      fullPath: '/demo/posthog'
      preLoaderRoute: typeof DemoPosthogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/': {
      id: '/$owner/$repo/'
      path: '/$owner/$repo'
      fullPath: '/$owner/$repo/'
      preLoaderRoute: typeof OwnerRepoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/chat/$chatId': {
      id: '/$owner/$repo/chat/$chatId'
      path: '/$owner/$repo/chat/$chatId'
      fullPath: '/$owner/$repo/chat/$chatId'
      preLoaderRoute: typeof OwnerRepoChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$repo/actions/runs/$runId': {
      id: '/$owner/$repo/actions/runs/$runId'
      path: '/$owner/$repo/actions/runs/$runId'
      fullPath: '/$owner/$repo/actions/runs/$runId'
      preLoaderRoute: typeof OwnerRepoActionsRunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  DemoPosthogRoute: DemoPosthogRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  OwnerRepoIndexRoute: OwnerRepoIndexRoute,
  OwnerRepoChatChatIdRoute: OwnerRepoChatChatIdRoute,
  OwnerRepoActionsRunsRunIdRoute: OwnerRepoActionsRunsRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
