/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsAgentIdSessionsSessionIdRouteImport } from './routes/agents.$agentId.sessions.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdSessionsSessionIdRoute =
  AgentsAgentIdSessionsSessionIdRouteImport.update({
    id: '/agents/$agentId/sessions/$sessionId',
    path: '/agents/$agentId/sessions/$sessionId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/$agentId/sessions/$sessionId': typeof AgentsAgentIdSessionsSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/$agentId/sessions/$sessionId': typeof AgentsAgentIdSessionsSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/$agentId/sessions/$sessionId': typeof AgentsAgentIdSessionsSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/agents/$agentId/sessions/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/agents/$agentId/sessions/$sessionId'
  id: '__root__' | '/' | '/agents/$agentId/sessions/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsAgentIdSessionsSessionIdRoute: typeof AgentsAgentIdSessionsSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/sessions/$sessionId': {
      id: '/agents/$agentId/sessions/$sessionId'
      path: '/agents/$agentId/sessions/$sessionId'
      fullPath: '/agents/$agentId/sessions/$sessionId'
      preLoaderRoute: typeof AgentsAgentIdSessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsAgentIdSessionsSessionIdRoute: AgentsAgentIdSessionsSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
